[package]
name = "rust-jit"
version = "0.0.0"
edition = "2021"

[dependencies]
ahash = "0.8"
inlinable_string = "0.1.15"
nix = { version = "0.27", features = ["mman", "feature", "signal"] }

[build-dependencies]
nom = "7.1"
nom-supreme = "0.8.0"

